# R visualization and statistics for the population genetics analysis.
#
# Linta Mahboob, MIPT (MSc thesis, supervisor Prof. Oleg Balanovsky).
# Analysis run 2021; script tidied up for sharing in 2025.
#
# Reproduces the ggplot2 figures from the thesis (MDS scatter, heatmap,
# dendrogram, focus panels, boxplots) and adds ANOVA/Tukey HSD tests on
# the regional distance distributions. Takes mds_coordinates.csv and
# group_distances.csv (output of script 02) plus pcAinfo.xlsx as input.
#
# Install packages once:
#   install.packages(c("tidyverse","ggrepel","readxl","pheatmap",
#                      "ggdendro","RColorBrewer","gridExtra","scales"))
#
# Usage: Rscript 03_R_visualization.R   (or source() from an R console)

# Load libraries
suppressPackageStartupMessages({
  library(tidyverse)
  library(ggrepel)
  library(readxl)
  library(pheatmap)
  library(ggdendro)
  library(RColorBrewer)
  library(gridExtra)
  library(scales)
})

# Configuration
OUT_DIR <- "./R_figures"
dir.create(OUT_DIR, showWarnings = FALSE, recursive = TRUE)

# Regional color palette — consistent with Python script
REGION_COLORS <- c(
  "South Asian"   = "#E63946",
  "West Asian"    = "#2196F3",
  "Central Asian" = "#4CAF50"
)

# Population to region mapping
SOUTH_ASIA   <- c("Indian","Pakistani","Afghani","Nepalease")
WEST_ASIA    <- c("Turkish","Iranian","Armenian","Lebanese","Cypriot",
                  "Israeli","Palestinian","Jordanian","Iraqi","Saudi",
                  "Syrian","Yemeni","Egypt","Azeri")
CENTRAL_ASIA <- c("Kazakh","Kyrgyz","Uzbeks","Turkmen","Tajik","Tajik_4M")

get_region <- function(group) {
  if (group %in% SOUTH_ASIA)    return("South Asian")
  if (group %in% WEST_ASIA)     return("West Asian")
  if (group %in% CENTRAL_ASIA)  return("Central Asian")
  return("Other")
}

cat("R population genetics visualization — South / West / Central Asian populations\n\n")

# Load data
cat("-- Loading data --\n")

# MDS coordinates (generated by Python script 02)
mds_df <- read.csv("mds_coordinates.csv", stringsAsFactors = FALSE)
mds_df$REGION <- sapply(mds_df$GROUP, get_region)
cat(sprintf("  MDS data: %d individuals, %d columns\n", nrow(mds_df), ncol(mds_df)))

# Population pairwise distances (generated by Python script 02)
gdist_raw <- read.csv("group_distances.csv", row.names = 1, check.names = FALSE)
gdist_mat  <- as.matrix(gdist_raw)
cat(sprintf("  Group distances: %d x %d matrix\n", nrow(gdist_mat), ncol(gdist_mat)))

# Sample metadata
meta <- read_excel("pcAinfo.xlsx")
meta$REGION <- sapply(meta$GROUP, get_region)
cat(sprintf("  Metadata: %d samples\n", nrow(meta)))

# Figure 1: ggplot2 MDS scatter plot
cat("\n-- Figure 1: ggplot2 MDS scatter plot --\n")

# Compute group centroids for labeling
centroids <- mds_df %>%
  group_by(GROUP, REGION) %>%
  summarise(
    MDS1 = mean(MDS1),
    MDS2 = mean(MDS2),
    MDS3 = mean(MDS3),
    .groups = "drop"
  )

# Panel A: MDS1 vs MDS2
p1a <- ggplot(mds_df, aes(x = MDS1, y = MDS2, color = REGION)) +
  geom_point(alpha = 0.45, size = 1.2, shape = 16) +
  geom_point(data = centroids, aes(x = MDS1, y = MDS2, color = REGION),
             shape = 8, size = 5, stroke = 1.2) +
  geom_label_repel(
    data = centroids,
    aes(x = MDS1, y = MDS2, label = GROUP, color = REGION),
    size = 3.0, fontface = "bold",
    fill = alpha("white", 0.75),
    label.padding = unit(0.15, "lines"),
    box.padding   = unit(0.2,  "lines"),
    max.overlaps  = 25,
    show.legend   = FALSE
  ) +
  scale_color_manual(values = REGION_COLORS, name = "Region") +
  labs(
    title    = "(a) MDS Axis 1 vs Axis 2",
    x        = "MDS Axis 1",
    y        = "MDS Axis 2"
  ) +
  theme_bw(base_size = 12) +
  theme(
    plot.title        = element_text(face = "bold", size = 13),
    axis.title        = element_text(face = "bold"),
    panel.background  = element_rect(fill = "#F8F9FA"),
    panel.grid.major  = element_line(linetype = "dashed", color = "#DDDDDD"),
    panel.grid.minor  = element_blank(),
    legend.position   = "bottom",
    legend.title      = element_text(face = "bold"),
    legend.background = element_rect(fill = "white", color = "#CCCCCC")
  )

# Panel B: MDS1 vs MDS3
p1b <- ggplot(mds_df, aes(x = MDS1, y = MDS3, color = REGION)) +
  geom_point(alpha = 0.45, size = 1.2, shape = 16) +
  geom_point(data = centroids, aes(x = MDS1, y = MDS3, color = REGION),
             shape = 8, size = 5, stroke = 1.2) +
  geom_label_repel(
    data = centroids,
    aes(x = MDS1, y = MDS3, label = GROUP, color = REGION),
    size = 3.0, fontface = "bold",
    fill = alpha("white", 0.75),
    label.padding = unit(0.15, "lines"),
    box.padding   = unit(0.2,  "lines"),
    max.overlaps  = 25,
    show.legend   = FALSE
  ) +
  scale_color_manual(values = REGION_COLORS, name = "Region") +
  labs(
    title    = "(b) MDS Axis 1 vs Axis 3",
    x        = "MDS Axis 1",
    y        = "MDS Axis 3"
  ) +
  theme_bw(base_size = 12) +
  theme(
    plot.title        = element_text(face = "bold", size = 13),
    axis.title        = element_text(face = "bold"),
    panel.background  = element_rect(fill = "#F8F9FA"),
    panel.grid.major  = element_line(linetype = "dashed", color = "#DDDDDD"),
    panel.grid.minor  = element_blank(),
    legend.position   = "bottom",
    legend.title      = element_text(face = "bold"),
    legend.background = element_rect(fill = "white", color = "#CCCCCC")
  )

fig1_combined <- grid.arrange(p1a, p1b, ncol = 2,
  top = grid::textGrob(
    "Figure 1. Multidimensional Scaling (MDS) of IBS Genetic Distances\nSouth, West and Central Asian Populations (n = 2,434; 24 groups)",
    gp = grid::gpar(fontsize = 14, fontface = "bold", col = "#1A3A5C")
  )
)
ggsave(
  file.path(OUT_DIR, "Fig1_MDS_ggplot.pdf"),
  plot   = fig1_combined,
  width  = 20, height = 9, units = "in", dpi = 300
)
cat("  Saved: Fig1_MDS_ggplot.pdf\n")

# Figure 2: pheatmap distance heatmap
cat("\n-- Figure 2: pheatmap distance heatmap --\n")

# Annotation for rows/columns
ann_col <- data.frame(
  Region = sapply(rownames(gdist_mat), get_region),
  row.names = rownames(gdist_mat)
)
ann_colors <- list(Region = REGION_COLORS)

pdf(file.path(OUT_DIR, "Fig2_Heatmap_R.pdf"), width = 14, height = 13)
pheatmap(
  gdist_mat,
  color              = colorRampPalette(rev(brewer.pal(11, "RdYlBu")))(100),
  clustering_method  = "average",
  annotation_row     = ann_col,
  annotation_col     = ann_col,
  annotation_colors  = ann_colors,
  fontsize_row       = 10,
  fontsize_col       = 10,
  fontsize           = 11,
  border_color       = "white",
  cellwidth          = 22,
  cellheight         = 22,
  treeheight_row     = 60,
  treeheight_col     = 60,
  legend             = TRUE,
  show_rownames      = TRUE,
  show_colnames      = TRUE,
  main               = paste0(
    "Figure 2. Pairwise Genetic Distance Heatmap Between Population Groups\n",
    "(Average IBS Distance, Hierarchically Clustered — Average Linkage)"
  )
)
dev.off()
cat("  Saved: Fig2_Heatmap_R.pdf\n")

# Figure 3: ggdendro hierarchical clustering dendrogram
cat("\n-- Figure 3: hierarchical clustering dendrogram --\n")

# Perform hierarchical clustering (average linkage)
hclust_obj <- hclust(as.dist(gdist_mat), method = "average")
dend_data   <- dendro_data(hclust_obj, type = "rectangle")

# Build label data with region colors
label_df <- dend_data$labels
label_df$region <- sapply(as.character(label_df$label), get_region)
label_df$color  <- REGION_COLORS[label_df$region]

p3 <- ggplot() +
  geom_segment(
    data = dend_data$segments,
    aes(x = x, y = y, xend = xend, yend = yend),
    linewidth = 0.6, color = "#444444"
  ) +
  geom_text(
    data = label_df,
    aes(x = x, y = y - 0.0001, label = label, color = region),
    angle = 40, hjust = 1, vjust = 1,
    size = 3.8, fontface = "bold"
  ) +
  scale_color_manual(values = REGION_COLORS, name = "Region") +
  scale_y_continuous(
    name   = "Average IBS Genetic Distance",
    expand = expansion(mult = c(0.35, 0.05))
  ) +
  labs(
    title = paste0(
      "Figure 3. Hierarchical Clustering Dendrogram of Asian Population Groups\n",
      "Based on Pairwise IBS Genetic Distances (n = 2,434; 24 groups)"
    ),
    x = NULL
  ) +
  theme_bw(base_size = 12) +
  theme(
    plot.title       = element_text(face = "bold", size = 13, color = "#1A3A5C"),
    axis.title.y     = element_text(face = "bold", size = 12),
    axis.text.x      = element_blank(),
    axis.ticks.x     = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor   = element_blank(),
    panel.background = element_rect(fill = "#F8F9FA"),
    legend.position  = "top",
    legend.title     = element_text(face = "bold")
  )

ggsave(
  file.path(OUT_DIR, "Fig3_Dendro_R.pdf"),
  plot   = p3,
  width  = 16, height = 8, units = "in", dpi = 300
)
cat("  Saved: Fig3_Dendro_R.pdf\n")

# Figure 4: focus panels (ggplot2)
cat("\n-- Figure 4: south asian focus MDS panels --\n")

focus_pak <- c("Pakistani","Afghani","Indian","Turkish","Tajik","Tajik_4M",
               "Kazakh","Kyrgyz","Uzbeks")
focus_ind <- c("Indian","Pakistani","Nepalease","Kazakh","Kyrgyz",
               "Uzbeks","Tajik","Tajik_4M")

make_focus_panel <- function(focus_groups, subtitle) {
  background <- mds_df
  foreground  <- mds_df %>% filter(GROUP %in% focus_groups)
  fg_centroids<- foreground %>%
    group_by(GROUP, REGION) %>%
    summarise(MDS1 = mean(MDS1), MDS2 = mean(MDS2), .groups = "drop")

  ggplot() +
    geom_point(data = background,  aes(x = MDS1, y = MDS2),
               color = "#CCCCCC", size = 1.0, alpha = 0.3) +
    geom_point(data = foreground,  aes(x = MDS1, y = MDS2, color = REGION),
               size = 2.0, alpha = 0.85) +
    geom_point(data = fg_centroids, aes(x = MDS1, y = MDS2, color = REGION),
               shape = 8, size = 6, stroke = 1.5) +
    geom_label_repel(
      data = fg_centroids,
      aes(x = MDS1, y = MDS2, label = GROUP, color = REGION),
      size = 3.5, fontface = "bold",
      fill = alpha("white", 0.8),
      box.padding = unit(0.3, "lines"),
      max.overlaps = 20,
      show.legend  = FALSE
    ) +
    scale_color_manual(values = REGION_COLORS, name = "Region") +
    labs(title = subtitle, x = "MDS Axis 1", y = "MDS Axis 2") +
    theme_bw(base_size = 12) +
    theme(
      plot.title       = element_text(face = "bold", size = 12),
      axis.title       = element_text(face = "bold"),
      panel.background = element_rect(fill = "#F8F9FA"),
      panel.grid.major = element_line(linetype = "dashed", color = "#DDDDDD"),
      panel.grid.minor = element_blank(),
      legend.position  = "bottom"
    )
}

p4a <- make_focus_panel(focus_pak, "(a) Pakistani Groups in Regional Context")
p4b <- make_focus_panel(focus_ind, "(b) Indian & Himalayan Groups in Regional Context")

fig4_combined <- grid.arrange(p4a, p4b, ncol = 2,
  top = grid::textGrob(
    "Figure 4. Regional Genetic Positioning: Focus on South Asian Populations",
    gp = grid::gpar(fontsize = 14, fontface = "bold", col = "#1A3A5C")
  )
)
ggsave(
  file.path(OUT_DIR, "Fig4_FocusPanel_R.pdf"),
  plot  = fig4_combined,
  width = 20, height = 9, units = "in", dpi = 300
)
cat("  Saved: Fig4_FocusPanel_R.pdf\n")

# Figure 5: boxplots (ggplot2)
cat("\n-- Figure 5: region distance boxplots (ggplot2) --\n")

# Build long-format dataframe for ggplot
region_pairs_list <- list(
  list(r1="South Asian",  r2="West Asian",    label="South vs West Asian"),
  list(r1="South Asian",  r2="Central Asian", label="South vs Central Asian"),
  list(r1="West Asian",   r2="Central Asian", label="West vs Central Asian")
)

build_boxplot_df <- function(rp) {
  r1 <- rp$r1; r2 <- rp$r2; lab <- rp$label
  g1  <- rownames(gdist_mat)[sapply(rownames(gdist_mat), get_region) == r1]
  g2  <- rownames(gdist_mat)[sapply(rownames(gdist_mat), get_region) == r2]
  btwn <- as.vector(gdist_mat[g1, g2])
  w1   <- diag(gdist_mat)[g1]; w1 <- w1[w1 > 0]
  w2   <- diag(gdist_mat)[g2]; w2 <- w2[w2 > 0]
  rbind(
    data.frame(value=w1,   group=paste0("Within\n",r1),  comparison=lab, color=REGION_COLORS[r1]),
    data.frame(value=w2,   group=paste0("Within\n",r2),  comparison=lab, color=REGION_COLORS[r2]),
    data.frame(value=btwn, group="Between\nRegions",      comparison=lab, color="#FF9800")
  )
}

box_df <- do.call(rbind, lapply(region_pairs_list, build_boxplot_df))

# Compute medians for annotation
medians <- box_df %>%
  group_by(comparison, group) %>%
  summarise(med = median(value), .groups = "drop")

p5 <- ggplot(box_df, aes(x = group, y = value, fill = group)) +
  geom_boxplot(alpha = 0.8, outlier.size = 1.2, outlier.alpha = 0.4,
               outlier.color = "#999999", width = 0.55) +
  geom_text(data = medians,
            aes(x = group, y = med + 0.0004, label = sprintf("%.4f", med)),
            fontface = "bold", size = 3.2, color = "#333333", inherit.aes = FALSE) +
  facet_wrap(~comparison, ncol = 3, scales = "free_x") +
  scale_fill_manual(values = c(
    setNames(REGION_COLORS["South Asian"],   paste0("Within\nSouth Asian")),
    setNames(REGION_COLORS["West Asian"],    paste0("Within\nWest Asian")),
    setNames(REGION_COLORS["Central Asian"], paste0("Within\nCentral Asian")),
    "Between\nRegions" = "#FF9800"
  ), guide = "none") +
  labs(
    title = paste0(
      "Figure 6. Within- and Between-Region Genetic Distance Distributions\n",
      "(IBS distance; median values annotated)"
    ),
    x = NULL, y = "IBS Genetic Distance"
  ) +
  theme_bw(base_size = 12) +
  theme(
    plot.title       = element_text(face = "bold", size = 13, color = "#1A3A5C"),
    axis.title.y     = element_text(face = "bold", size = 12),
    axis.text.x      = element_text(face = "bold", size = 10),
    strip.text       = element_text(face = "bold", size = 11),
    panel.background = element_rect(fill = "#F8F9FA"),
    panel.grid.major.y = element_line(linetype = "dashed", color = "#DDDDDD"),
    panel.grid.major.x = element_blank(),
    panel.grid.minor   = element_blank()
  )

ggsave(
  file.path(OUT_DIR, "Fig5_Boxplots_R.pdf"),
  plot  = p5,
  width = 18, height = 7, units = "in", dpi = 300
)
cat("  Saved: Fig5_Boxplots_R.pdf\n")

# Statistical Analysis: ANOVA and pairwise tests on IBS distances
cat("\n-- Statistical Tests: ANOVA and pairwise comparisons --\n")

sink(file.path(OUT_DIR, "Region_ANOVA_results.txt"))
cat("IBS distance comparisons by region\n\n")

# Build individual-level distance summary
# (using between-group level distances from the 24x24 matrix)
all_dist_df <- do.call(rbind, lapply(region_pairs_list, build_boxplot_df))

cat("-- One-way ANOVA: does region explain between-group IBS distance? --\n")
anova_model <- aov(value ~ group, data = all_dist_df)
print(summary(anova_model))

cat("\n-- Tukey HSD Post-hoc: pairwise regional comparisons --\n")
tukey_result <- TukeyHSD(anova_model)
print(tukey_result)

cat("\n-- Descriptive statistics by group --\n")
desc_stats <- all_dist_df %>%
  group_by(comparison, group) %>%
  summarise(
    N       = n(),
    Mean    = round(mean(value),   4),
    Median  = round(median(value), 4),
    SD      = round(sd(value),     4),
    Min     = round(min(value),    4),
    Max     = round(max(value),    4),
    .groups = "drop"
  )
print(as.data.frame(desc_stats), row.names = FALSE)

sink()
cat("  Saved: Region_ANOVA_results.txt\n")

# Summary table (CSV export)
cat("\n-- Exporting table 1 summary statistics --\n")

groups_vec <- rownames(gdist_mat)
summary_rows <- lapply(groups_vec, function(grp) {
  region  <- get_region(grp)
  n       <- sum(meta$GROUP == grp)
  wd      <- gdist_mat[grp, grp]
  others  <- gdist_mat[grp, colnames(gdist_mat) != grp]
  md      <- mean(others)
  nearest <- names(which.min(others))
  nd      <- min(others)
  data.frame(
    Population           = grp,
    Region               = region,
    N                    = n,
    Within_group_IBS     = round(wd, 4),
    Mean_dist_to_others  = round(md, 4),
    Nearest_population   = nearest,
    Nearest_IBS_distance = round(nd, 4),
    stringsAsFactors     = FALSE
  )
})

summary_table <- do.call(rbind, summary_rows)
summary_table <- summary_table[order(summary_table$Region, summary_table$Population), ]

write.csv(summary_table,
          file.path(OUT_DIR, "Table1_stats.csv"),
          row.names = FALSE)
cat("  Saved: Table1_stats.csv\n")
print(summary_table, row.names = FALSE)

# Session info (for reproducibility)
cat("\n-- Session information --\n")
sink(file.path(OUT_DIR, "session_info.txt"))
cat("R Session Information — for reproducibility\n")
cat("Generated:", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\n\n")
print(sessionInfo())
sink()

cat("  Saved: session_info.txt\n")
cat(sprintf("\nDone. All outputs saved to: %s/\n", OUT_DIR))
